# Generated by Django 4.2.19 on 2025-03-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_image_type_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
