# Generated by Django 4.2.19 on 2025-03-03 19:16

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=community.models.post_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=community.models.post_thumbnail_path),
        ),
    ]
