# Generated by Django 4.2.19 on 2025-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_post_options_post_likes_users_alter_like_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='图片URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='缩略图URL'),
        ),
    ]
