# Generated by Django 4.2.19 on 2025-03-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_post_image_url_post_thumbnail_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_url',
            new_name='image_url_field',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail_url',
            new_name='thumbnail_url_field',
        ),
    ]
