# Generated by Django 4.2.19 on 2025-03-08 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0003_weightrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.FloatField(blank=True, help_text='Target weight in kg', null=True)),
                ('weight_goal_date', models.DateField(blank=True, help_text='Target date to achieve weight goal', null=True)),
                ('daily_steps_goal', models.PositiveIntegerField(blank=True, help_text='Daily steps goal', null=True)),
                ('daily_sleep_hours_goal', models.PositiveIntegerField(blank=True, help_text='Daily sleep hours goal', null=True)),
                ('daily_sleep_minutes_goal', models.PositiveIntegerField(blank=True, default=0, help_text='Additional minutes for sleep goal', null=True)),
                ('weekly_running_distance_goal', models.FloatField(blank=True, help_text='Weekly running distance goal in km', null=True)),
                ('weekly_running_sessions_goal', models.PositiveIntegerField(blank=True, help_text='Number of running sessions per week', null=True)),
                ('weekly_training_sessions_goal', models.PositiveIntegerField(blank=True, help_text='Number of training sessions per week', null=True)),
                ('daily_calories_goal', models.PositiveIntegerField(blank=True, help_text='Daily calories intake goal', null=True)),
                ('daily_protein_goal', models.FloatField(blank=True, help_text='Daily protein intake goal in grams', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Goal',
                'verbose_name_plural': 'Health Goals',
            },
        ),
    ]
