name: Deploy Django to Server

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: WellLog
        auto-update-conda: true
        python-version: "3.10"

    - name: Install dependencies with Conda
      shell: bash -l {0}
      run: |
        # conda install -c conda-forge --file conda-requirements.txt
        pip install -r requirements.txt

    - name: Run tests
      shell: bash -l {0}
      run: |
        python manage.py test --keepdb

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/WellLog
          git pull origin main

          source /opt/miniconda3/bin/activate WellLog
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py migrate
          sudo systemctl restart gunicorn
          sudo systemctl reload nginx
