name: Deploy Django to Server

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2  # 使用 Conda 官方 Action
      with:
        miniconda-version: "latest"
        activate-environment: WellLog
        auto-update-conda: true
        python-version: "3.10"

    - name: Install dependencies with Conda
      shell: bash -l {0}  # 必须使用 login shell 以激活 Conda
      run: |
        # conda install -c conda-forge --file conda-requirements.txt  # 如果使用 Conda 包
        pip install -r requirements.txt  # 补充安装 PyPI 包

    - name: Run tests
      shell: bash -l {0}
      run: |
        python manage.py test

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/WellLog
          git pull origin main
          # 激活 Conda 环境并重启服务
          source /opt/miniconda3/bin/activate WellLog
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py migrate
          sudo systemctl restart gunicorn
          sudo systemctl reload nginx
